### ISSUE TITLE
Resolve loading of other packages used by spammR

### ISSUE THREAD

**Issue by HarkiratSohi** [PNNL-CompBio/spammR#26]
Some packages that are needed for spammR to run don't seem to get loaded when spammR in installed in R, even though these are imported in the function definitions and also show in the NAMESPACE of the spammR pacakge.
Noticed this for packages SpatialExperiment and writexl.
Current work-around has been to load any missed package dependencies locally in R.

**Comment by sgosline** [comment]
Fixed in current data-ingest branch.
