### ISSUE TITLE
Load Pancreas dataset with tissue image(s) and metadata file

### ISSUE THREAD

**Issue by HarkiratSohi** [PNNL-CompBio/spammR#27]
To be used in the package vignette if can't use Tujin's mouse brain ROI spatial proteomics data. 

How to organize metadata? 
If there are multiple images, I think we talked about calling the samples from the same region from multiple images as replicates. To represent all replicates' data in a single spatial heatmap (generated by the spammR spatial_heatmap function), only one background tissue image will be displayed even if the samples come from multiple tissue images. Must indicate which image this should be. 

The spatial experiment object can store multiple background images and we can specify any one that we want for the spatial heatmap background.

**Comment by sgosline** [comment]
Currently being tracked in data-ingest branch.
