### ISSUE TITLE
Check about incorporating mouse geneset databases directly into leapR; making sure spammR::enrich_ora() still runs.

### ISSUE THREAD

**Issue by HarkiratSohi** [PNNL-CompBio/spammR#28]
Currently enrich_ora() accesses these mouse geneset database files as pre-made LeapR compatible files, accessible by a local file path. 

LeapR currently does not come with mouse geneset database files.

**Comment by sgosline** [comment]
Another issue is that example data is now human, so we need to make sure code can run with human attributes.

**Comment by sgosline** [comment]
Fixed this in a Pull request on the leapR project: https://github.com/pnnl/leapR/pull/44
